version: "3.9"
services:
  app:
    image: ecommerce-app
    container_name: ecommerce-app
    restart: always
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/project
  db:
    image: postgres:14.4
    container_name: postgresql-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
